apiVersion: v1
kind: Service
metadata:
  name: adminer-svc
  labels:
    name: adminer
spec:
  type: NodePort
  selector:
    matchLabels:
      app: taa
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
