apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-dpl
  labels:
    app: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: db
        image: mysql
        resources:
        ports:
        - containerPort: 3306
      env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: taa-cfm
              key: db_pw
        - name: MYSQL_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: taa-cfm
              key: db_pw
        - name: MYSQL_USER
          valueFrom:
            configMapKeyRef:
              name: taa-cfm
              key: db_user
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: taa-cfm
              key: db_name
