apiVersion: v1
kind: Service
metadata:
  name: db-svc
  labels:
    name: taa
spec:
  type: ClusterIP
  selector:
    matchLabels:
      app: taa
  ports: 
    - protocol: tcp
      port: 3306
      targetPort: 3306
