apiVersion: batch/v1
kind: Job
metadata:
  name: add-job
spec:
  completions: 1
  template:
    spec:
      containers:
      - name: add-ctn
        image: phund1001/php:latest
        command: ["php", "artisan", "db:seed", "--class=DatabaseSeeder"]
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-cfm
              key: db_host
        - name: DB_DATABASE
          valueFrom:
            configMapKeyRef:
              name: db-cfm
              key: db_name
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: db-cfm
              key: db_user
        - name: DB_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: db-cfm
              key: db_pw
      restartPolicy: Never