apiVersion: apps/v1
kind: Deployment
metadata:
  name: taa-dpl
  labels:
    app: taa
spec:
  replicas: 2
  selector:
    matchLabels:
      app: taa
  template:
    metadata:
      labels:
        app: taa
    spec:
      containers:
      - name: taa-nginx
        image: phund1001/nginix:latest
        resources:
        ports:
        - containerPort: 80
      -name: taa-php
        image: phund1001/php:latest
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-cfm
              key: db_host
        - name: DB_DATABASE
          valueFrom:
            configMapKeyRef:
              name: db-cfm
              key: db_name
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: db-cfm
              key: db_user
        - name: DB_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: db-cfm
              key: db_pw
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 2
