apiVersion: v1
kind: Service
metadata:
  name: taa-svc
  labels:
    name: taa
spec:
  type: NodePort
  selector:
    matchLabels:
      app: taa
  ports: 
    - protocol: TCP
      port: 80
      targetPort: 80
